### PR TITLE
'Changing-svg-logo'

### PR DESCRIPTION
**Pull request by arielbouskila**
adding the 2 logos hebrew & english into Images folder
adding 2 objects in en and he in the header.html template

### CODE REVIEW

**Comment by daonb** [comment]
Thanks for the pull request!

I've been looking at the template you've changed - [header.html](https://github.com/Beit-Hatfutsot/dbs-front/blob/dev/templates/main/header.html] - we already got two method of using svg there and I don't want to add a third as things are too confusing as it is.
The way I like is what's done on line 30: include a single html file that contains both the Hebrew & English svg commands. Can you please create a single HTML file, copy the two svgs code in there and `ng-include` it in the template?

Benny

**Comment by arielbouskila** [comment]
Done, i have removed the 2 svg files and added a new html file that includes the 2 svg , used ng-include in header.html.

**Comment by daonb** [comment]
Thanks!

**Comment by Inna-r** [comment]
#154

**Pull request merged**
